# Config file for Air
[build]
  # Command to build the app
  cmd = "swag init -g ./cmd/api/main.go -o ./cmd/docs"
  full_bin = "sleep 2 && go build -o ./tmp/main ./cmd/api/main.go && ./tmp/main"
  # Binary to watch
  bin = "./tmp/main"
  # Working directory
  dir = "."
  # Patterns to watch
  include_ext = ["go"]
  # Exclude files
  exclude_dir = ["vendor", "cmd/docs"]
  delay = 2000

[log]
  level = "debug"
