# Configuração de build
[build]
  # Comando para construir o binário
  cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
  # Binary to watch
  bin = "./tmp/main.exe"
  # Diretório de trabalho
  dir = "."
  # Extensões de arquivos a serem monitoradas
  include_ext = ["go"]
  # Diretórios a serem excluídos do monitoramento
  exclude_dir = ["vendor"]

# Configuração de log
[log]
  # Nível de log (debug, info, warn, error, fatal, panic)
  level = "debug"

# Configuração de hot reload
[misc]
  # Limpar o console antes de cada reconstrução
  clear_on_rebuild = true
