version: '3.8'
services:
  api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3333:3333"
      volumes:
        - .:/app
      depends_on:
        - db
      networks:
        - rc-services-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: web-gin
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/rcdata/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rc-services-network

volumes:
  postgres_data:

networks:
  rc-services-network: