version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - ecomhub_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ehgateway
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/ehdata/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecomhub_network

volumes:
  postgres_data:

networks:
  ecomhub_network:
    name: ecomhub_services_network
