host: localhost:3333
info:
  contact: {}
  description: Esta é a API da Web App.
  title: Web App API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Verifica se o servidor está ativo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Ping
      tags:
      - RCGateway-api
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
